### ISSUE TITLE
大佬web访页面的时候能添加个🔒的页面么

### ISSUE THREAD

**Issue by logdns** [RICwang/docker-wechat#11]
大佬web访页面的时候能添加个🔒的页面么
怕被人扫到,是不是 就可以看到微信信息啦

**Comment by RICwang** [comment]
参考这个
环境变量 | 描述 | 默认值
-- | -- | --
WEB_AUTHENTICATION | 当设置为1时，通过网络浏览器访问应用程序GUI时需要通过登录页面进行保护。只有提供有效凭据才允许访问。注意：此功能需要启用安全连接（SECURE_CONNECTION环境变量）。 | 0
WEB_AUTHENTICATION_USERNAME | Web认证的可选用户名配置。这是为单个用户配置凭据的快速简便方法。要以更安全的方式配置凭据或添加更多用户，请参见Web认证部分。 | （无值）
WEB_AUTHENTICATION_PASSWORD | Web认证的可选密码配置。这是为单个用户配置凭据的快速简便方法。要以更安全的方式配置凭据或添加更多用户，请参见Web认证部分。 | （无值）
SECURE_CONNECTION | 当设置为1时，使用加密连接访问应用程序的GUI（通过网络浏览器或VNC客户端）。更多详情请参见安全部分。 | 0
SECURE_CONNECTION_VNC_METHOD | 执行安全VNC连接的方法。可能的值为SSL或TLS。更多详情请参见安全部分。 | SSL
SECURE_CONNECTION_CERTS_CHECK_INTERVAL | 系统验证Web或VNC证书是否已更改的间隔时间（秒）。当检测到更改时，受影响的服务会自动重启。值为0时禁用检查。 | 60

**Comment by logdns** [comment]
感谢大佬, 不好意思 我眼拙 没有仔细看 ,谢谢

**Comment by longerpt** [comment]
**您好，我配置了web访问凭据后，一直显示用户名密码错误，是什么原因呢？

密码我更换了很多种类都是一样，求解**

services:
 wechat:
  image: ricwang/docker-wechat:latest
  container_name: wechat_container_demo
  volumes:
    - /volume1/docker/wechat/.xwechat:/root/.xwechat
    - /volume1/docker/wechat/xwechat_files:/root/xwechat_files
    - /volume1/docker/wechat/download:/root/download
    #- /dev/snd:/dev/snd
  ports:
    - "6880:5800"
    - "6990:5900"
  environment:
    - LANG=zh_CN.UTF-8
    - USER_ID=0
    - GROUP_ID=0
    - WEB_AUDIO=1
    - TZ=Asia/Shanghai
    - SECURE_CONNECTION=1
    - WEB_AUTHENTICATION=1
    - WEB_AUTHENTICATION_DEFAULT_USERNAME=xxxxx
    - WEB_AUTHENTICATION_DEFAULT_PASSWORD=xxxxx..
    - VNC_PASSWORD=xxxxxx..
  network_mode: bridge
  privileged: true
  restart: always

![image](https://github.com/user-attachments/assets/047c5405-7e4f-4345-8785-ab68aeae8dec)
