### ISSUE TITLE
有没有办法实现对外API接口

### ISSUE THREAD

**Issue by keshiyong** [RICwang/docker-wechat#2]
类似这种https://github.com/danni-cool/wechatbot-webhook

**Comment by RICwang** [comment]
> 类似这种https://github.com/danni-cool/wechatbot-webhook

这不是现成的项目吗？用人家的就行，别重复造轮子了

**Comment by wangjueszu** [comment]
我觉得不一样吧，上面的看上去是web版本的。web版本的有些微信号是不支持的，还容易掉线
